/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Toolkit;

/**
 *
 * @author faria
 */
public class JFrameGui extends javax.swing.JFrame {

    /**
     * Creates new form JFrameGui
     */
    public JFrameGui() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel_Mengo = new javax.swing.JLabel();
        JDesktopPane_Painel = new javax.swing.JDesktopPane();
        JLabel_Foto = new javax.swing.JLabel();
        JMenuPrincipal = new javax.swing.JMenuBar();
        JMenu_Piramede = new javax.swing.JMenu();
        JMenuItem_Piramide = new javax.swing.JMenuItem();
        JMenu_Esfera = new javax.swing.JMenu();
        JMenuItem_Esfera = new javax.swing.JMenuItem();
        JMenu_Retangulo = new javax.swing.JMenu();
        JMenuItem_Retangulo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JLabel_Mengo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo do mengo.png"))); // NOI18N

        JDesktopPane_Painel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout JDesktopPane_PainelLayout = new javax.swing.GroupLayout(JDesktopPane_Painel);
        JDesktopPane_Painel.setLayout(JDesktopPane_PainelLayout);
        JDesktopPane_PainelLayout.setHorizontalGroup(
            JDesktopPane_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );
        JDesktopPane_PainelLayout.setVerticalGroup(
            JDesktopPane_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        JLabel_Foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagem do WhatsApp de 2024-03-06 à(s) 15.10.38_6b7ee392_resized.jpg"))); // NOI18N
        JLabel_Foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JMenu_Piramede.setText("Piramide");
        JMenu_Piramede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenu_PiramedeActionPerformed(evt);
            }
        });

        JMenuItem_Piramide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/piramede_resized.png"))); // NOI18N
        JMenuItem_Piramide.setText("CALCULAR");
        JMenuItem_Piramide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_PiramideActionPerformed(evt);
            }
        });
        JMenu_Piramede.add(JMenuItem_Piramide);

        JMenuPrincipal.add(JMenu_Piramede);

        JMenu_Esfera.setText("Esfera");
        JMenu_Esfera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenu_EsferaActionPerformed(evt);
            }
        });

        JMenuItem_Esfera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/esfera_resized.png"))); // NOI18N
        JMenuItem_Esfera.setText("CALCULAR");
        JMenuItem_Esfera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_EsferaActionPerformed(evt);
            }
        });
        JMenu_Esfera.add(JMenuItem_Esfera);

        JMenuPrincipal.add(JMenu_Esfera);

        JMenu_Retangulo.setText("Retangulo");
        JMenu_Retangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenu_RetanguloActionPerformed(evt);
            }
        });

        JMenuItem_Retangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/retangulo_resized.png"))); // NOI18N
        JMenuItem_Retangulo.setText("CALCULAR");
        JMenuItem_Retangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_RetanguloActionPerformed(evt);
            }
        });
        JMenu_Retangulo.add(JMenuItem_Retangulo);

        JMenuPrincipal.add(JMenu_Retangulo);

        setJMenuBar(JMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(JDesktopPane_Painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabel_Mengo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabel_Foto, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabel_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLabel_Mengo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(JDesktopPane_Painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMenu_PiramedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenu_PiramedeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JMenu_PiramedeActionPerformed

    private void JMenu_EsferaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenu_EsferaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JMenu_EsferaActionPerformed

    private void JMenu_RetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenu_RetanguloActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JMenu_RetanguloActionPerformed

    private void JMenuItem_PiramideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_PiramideActionPerformed
        // TODO add your handling code here:
        JInternalFrame_Piramide obj1 = new JInternalFrame_Piramide();
        JDesktopPane_Painel.add(obj1);
        obj1.setVisible(true);
        
    }//GEN-LAST:event_JMenuItem_PiramideActionPerformed

    private void JMenuItem_EsferaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_EsferaActionPerformed
        // TODO add your handling code here:
        JInternalFrame_Esfera obj2 = new JInternalFrame_Esfera();
        JDesktopPane_Painel.add(obj2);
        obj2.setVisible(true);
    }//GEN-LAST:event_JMenuItem_EsferaActionPerformed

    private void JMenuItem_RetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_RetanguloActionPerformed
        // TODO add your handling code here:
        JInternalFrame_Retangulo obj3 = new JInternalFrame_Retangulo();
        JDesktopPane_Painel.add(obj3);
        obj3.setVisible(true);
    }//GEN-LAST:event_JMenuItem_RetanguloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFrameGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDesktopPane_Painel;
    private javax.swing.JLabel JLabel_Foto;
    private javax.swing.JLabel JLabel_Mengo;
    private javax.swing.JMenuItem JMenuItem_Esfera;
    private javax.swing.JMenuItem JMenuItem_Piramide;
    private javax.swing.JMenuItem JMenuItem_Retangulo;
    private javax.swing.JMenuBar JMenuPrincipal;
    private javax.swing.JMenu JMenu_Esfera;
    private javax.swing.JMenu JMenu_Piramede;
    private javax.swing.JMenu JMenu_Retangulo;
    // End of variables declaration//GEN-END:variables

    

}
